version: '3.4'

services:
  redis:
    image: redis:latest
  
  pd0:
    image: pingcap/pd:v6.1.5
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd0
      - --data-dir=/data/pd0
      - --client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://pd0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-peer-urls=http://pd0:2380
      - --log-file=/logs/pd0.log
    restart: on-failure
  
  tikv0:
    image: pingcap/tikv:v6.1.5
    ports:
      - "20160:20160"
    volumes:
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
    restart: always
  
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: 
      - start
      - --log=debug
      - --user=root
      - --pass=root
      - tikv://pd0:2379
    depends_on:
      - tikv0
    restart: always
  
  haltion:
    image: haltion
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - tikv0
      - redis
    restart: always
